@startuml Domain model
left to right direction

class roles {
    +id : integer 
    +name : string 
}

class users {
    +id : integer 
    +login : string 
    +password : string
    +FIO : string
    +role_id : integer
    +employee_id : integer
    +active : boolean
}

class employees {
    +id : integer 
    +FIO : string
    +position_id : integer
    +branch_id : integer 
}

class positions {
    +id : integer 
    +name : string 
}

class branches {
    +id : integer 
    +name : string
    +legal_address : string
    +current_address : string 
}

class parts {
    +id : integer 
    +name : string 
    +article : string
    +manufacturer_id : integer
    +dealer_id : integer
    +price : integer
}

class manufacturers {
    +id : integer 
    +name : string 
}

class dealers {
    +id : integer 
    +name : string 
}

class warehouse {
    +id : integer 
    +name : string
    +branch_id : integer
    +address_accounting : boolean 
}

class address {
    +id : integer 
    +area_id : integer
    +rack_id : integer
    +cell_id : integer 
}

class areas {
    +id : integer 
    +name : string 
}

class racks {
    +id : integer 
    +name : string 
}

class cells {
    +id : integer 
    +name : string 
}

class typeDocs {
    +id : integer 
    +name : string 
}

class DocsWarehouses {
    +id : integer 
    +employee_id : integer
    +type_id : integer
    +doc_date : date 
    +order_id : integer
}

class recordsDocsWarehouses {
    +id : integer 
    +docs_id : integer
    +part_id : integer
    +address_id : integer
    +warehouse_id : integer
    +quantity : integer
}

class orders {
    +id : integer 
    +employee_id : integer
    +order_date : date
    +warehouse_id : integer 
}

class recordOrders {
    +id : integer 
    +part_id : integer
    quantity : integer 
}

class purchases {
    +id : integer 
    +employee_id : integer
    +purchase_date : date
    +status_id : integer
}

class statusesPurchase {
    +id : integer 
    +name : string 
}

class recordsPurchase {
    +id : integer 
    +purchase_id : integer
    +part_id : integer
    +order_id : integer
    +quantity : integer 
}

class forecasts {
    +id : integer
    +employee_id : integer 
    +forecast_date : date 
}

class recordsForecasts {
    +id : integer 
    +forecast_id : integer
    +part_id : integer    
    +quantity : integer 
}

class docsReserve {
    +id : integer
    +employee_id : integer 
    +reserve_date : date 
    +cancel : boolean
}

class recordsDocsReserve {
    +id : integer 
    +reserve_id : integer
    +part_id : integer  
    +order_id : integer
    +warehouse_id : integer 
    +quantity : integer 
}

class docsTransfer {
    +id : integer
    +employee_id : integer 
    +source_warehouse_id : integer
    +destination_warehouse_id : integer 
    +transfer_date : date
}

class recordsDocsTransfer {
    +id : integer 
    +transfer_id : integer
    +part_id : integer 
    +order_id : integer   
    +quantity : integer 
}

employees::id "1" -- "1" users::employee_id
employees::id "1" -- "1..*" DocsWarehouses::employee_id
employees::id "1" -- "1..*" orders::employee_id
employees::id "1" -- "1..*" forecasts::employee_id
employees::id "1" -- "1..*" docsReserve::employee_id
employees::id "1" -- "1..*" docsTransfer::employee_id
employees::id "1" -- "1..*" purchases::employee_id
roles::id "1" -- "1..*" users::role_id 
positions::id "1" -- "1..*" employees::position_id
branches::id "1" -- "1..*" employees::branch_id

parts::manufacturer_id "1..*" -- "1" manufacturers::id
parts::dealer_id "1..*" -- "1" dealers::id
parts::id "1" -- "1..*" recordsDocsWarehouses::part_id
parts::id "1" -- "1..*" recordsDocsTransfer::part_id
parts::id "1" -- "1..*" recordOrders::part_id
parts::id "1" -- "1..*" recordsPurchase::part_id
parts::id "1" -- "1..*" recordsDocsReserve::part_id
parts::id "1" -- "1..*" recordsForecasts::part_id

branches::id "1" -- "1..*" warehouse::branch_id
warehouse::id "1" -- "1..*" recordsDocsWarehouses::warehouse_id
warehouse::id "1" -- "1..*" orders::warehouse_id
warehouse::id "1" -- "1..*" recordsDocsReserve::warehouse_id
warehouse::id "1" -- "1..*" docsTransfer::source_warehouse_id
warehouse::id "1" -- "1..*" docsTransfer::destination_warehouse_id
address::area_id "1..*" -- "1" areas::id
address::area_id "1..*" -- "1" racks::rack_id
address::area_id "1..*" -- "1" cells::cell_id
address::id "1" -- "0..*" recordsDocsWarehouses::address_id

typeDocs::id "1" -- "1..*" DocsWarehouses::type_id
orders::id "1" -- "1..*" DocsWarehouses::order_id
orders::id "1" -- "1..*" recordOrders::order_id
orders::id "1" -- "1..*" recordsPurchase::order_id
orders::id "1" -- "1..*" recordsDocsReserve::order_id
orders::id "1" -- "1..*" recordsDocsTransfer::order_id

forecasts::id "1" -- "1..*" recordsForecasts::forecast_id
docsReserve::id "1" -- "1..*" recordsDocsReserve::reserve_id
docsTransfer::id "1" -- "1..*" recordsDocsTransfer::transfer_id
purchases::id "1" -- "1..*" recordsPurchase::purchase_id
purchases::status_id "1..*" -- "1" statusesPurchase::id


@enduml