@startuml Domain model
left to right direction

class role {
    +id : integer 
    +name : string 
}

class user {
    +id : integer 
    +login : string 
    +password : string
    +FIO : string
    +role_id : integer
    +employee_id : integer
    +active : boolean
}

class employee {
    +id : integer 
    +FIO : string
    +position_id : integer
    +branch_id : integer 
}

class position {
    +id : integer 
    +name : string 
}

class branche {
    +id : integer 
    +name : string
    +legal_address : string
    +current_address : string 
}

class part {
    +id : integer 
    +name : string 
    +article : string
    +manufacturer_id : integer
    +dealer_id : integer
    +price : integer
}

class manufacturer {
    +id : integer 
    +name : string 
}

class dealer {
    +id : integer 
    +name : string 
}

class warehouse {
    +id : integer 
    +name : string
    +branch_id : integer
    +address_accounting : boolean 
}

class address {
    +id : integer 
    +area_id : integer
    +rack_id : integer
    +cell_id : integer 
}

class area {
    +id : integer 
    +name : string 
}

class rack {
    +id : integer 
    +name : string 
}

class cell {
    +id : integer 
    +name : string 
}

class typeDocs {
    +id : integer 
    +name : string 
}

class docWarehouse {
    +id : integer 
    +employee_id : integer
    +type_id : integer
    +doc_date : date 
    +order_id : integer
}

class recordDocWarehouse {
    +id : integer 
    +docs_id : integer
    +part_id : integer
    +address_id : integer
    +warehouse_id : integer
    +quantity : integer
}

class order {
    +id : integer 
    +employee_id : integer
    +order_date : date
    +warehouse_id : integer 
}

class recordOrder {
    +id : integer 
    +part_id : integer
    quantity : integer 
}

class purchase {
    +id : integer 
    +employee_id : integer
    +purchase_date : date
    +status_id : integer
}

class statusePurchase {
    +id : integer 
    +name : string 
}

class recordPurchase {
    +id : integer 
    +purchase_id : integer
    +part_id : integer
    +order_id : integer
    +quantity : integer 
}

class forecast {
    +id : integer
    +employee_id : integer 
    +forecast_date : date 
}

class recordForecast {
    +id : integer 
    +forecast_id : integer
    +part_id : integer    
    +quantity : integer 
}

class docReserve {
    +id : integer
    +employee_id : integer 
    +reserve_date : date 
    +cancel : boolean
}

class recordDocReserve {
    +id : integer 
    +reserve_id : integer
    +part_id : integer  
    +order_id : integer
    +warehouse_id : integer 
    +quantity : integer 
}

class docTransfer {
    +id : integer
    +employee_id : integer 
    +source_warehouse_id : integer
    +destination_warehouse_id : integer 
    +transfer_date : date
}

class recordDocTransfer {
    +id : integer 
    +transfer_id : integer
    +part_id : integer 
    +order_id : integer   
    +quantity : integer
}

employee::id "1" -- "1" user::employee_id
employee::id "1" -- "1..*" docWarehouse::employee_id
employee::id "1" -- "1..*" order::employee_id
employee::id "1" -- "1..*" forecast::employee_id
employee::id "1" -- "1..*" docReserve::employee_id
employee::id "1" -- "1..*" docTransfer::employee_id
employee::id "1" -- "1..*" purchase::employee_id
role::id "1" -- "1..*" user::role_id 
position::id "1" -- "1..*" employee::position_id
branche::id "1" -- "1..*" employee::branch_id

part::manufacturer_id "1..*" -- "1" manufacturer::id
part::dealer_id "1..*" -- "1" dealer::id
part::id "1" -- "1..*" recordDocWarehouse::part_id
part::id "1" -- "1..*" recordDocTransfer::part_id
part::id "1" -- "1..*" recordOrder::part_id
part::id "1" -- "1..*" recordPurchase::part_id
part::id "1" -- "1..*" recordDocReserve::part_id
part::id "1" -- "1..*" recordForecast::part_id

branche::id "1" -- "1..*" warehouse::branch_id
warehouse::id "1" -- "1..*" recordDocWarehouse::warehouse_id
warehouse::id "1" -- "1..*" order::warehouse_id
warehouse::id "1" -- "1..*" recordDocReserve::warehouse_id
warehouse::id "1" -- "1..*" docTransfer::source_warehouse_id
warehouse::id "1" -- "1..*" docTransfer::destination_warehouse_id
address::area_id "1..*" -- "1" area::id
address::area_id "1..*" -- "1" rack::rack_id
address::area_id "1..*" -- "1" cell::cell_id
address::id "1" -- "0..*" recordDocWarehouse::address_id

typeDocs::id "1" -- "1..*" docWarehouse::type_id
order::id "1" -- "1..*" docWarehouse::order_id
order::id "1" -- "1..*" recordOrder::order_id
order::id "1" -- "1..*" recordPurchase::order_id
order::id "1" -- "1..*" recordDocReserve::order_id
order::id "1" -- "1..*" recordDocTransfer::order_id

forecast::id "1" -- "1..*" recordForecast::forecast_id
docReserve::id "1" -- "1..*" recordDocReserve::reserve_id
docTransfer::id "1" -- "1..*" recordDocTransfer::transfer_id
purchase::id "1" -- "1..*" recordPurchase::purchase_id
purchase::status_id "1..*" -- "1" statusePurchase::id


@enduml