@startuml sequence euroavto

skinparam SequenceMessageAlignment center

participant STO
participant Dealer

activate STO
activate Dealer
STO -> Dealer : 1. Ввод логина и пароля (POST /auth)

activate Dealer

alt данные валидны

    Dealer -> Dealer : проверка данных

    Dealer --> STO : 1.1 токен 
    deactivate Dealer

    STO -> Dealer : 2. Получить предложения (GET /offers/products/{product_id,...}
    activate Dealer

    Dealer --> STO : 2.1 Список подобранных запчастей
    deactivate Dealer

        loop не все запчасти добавлены в корзину

            STO -> Dealer : 3. Добавить в корзину (POST /carts/offers/{offer_id})
            activate Dealer
            Dealer -> Dealer : сохранение в корзине
            Dealer --> STO : 3.1 товар добавлен, информация о корзине  
            deactivate Dealer          

        end

        loop количество запчастей не установлено

            STO -> Dealer : 4. Изменить количество товара в корзине PUT /carts/offers/{offer_id}
            activate Dealer
            Dealer -> Dealer : изменение количества в корзине
            Dealer --> STO : 4.1 количество изменено, информация о корзине
            deactivate Dealer

        end

        opt необходимо удалить товар из корзины

            Dealer -> STO : 5. Удалить товар из корзины (DELETE /carts/offers/{offer_id})
            activate Dealer
            Dealer -> Dealer : изменение корзины
            Dealer --> STO : 5.1 товар удален, информация о корзине 
            deactivate Dealer

        end
    STO -> Dealer: 6. Заказать товары из корзины (POST /orders/carts)
    activate Dealer
    Dealer -> Dealer : сохранение заказа
    Dealer --> STO : 6.1 Заказ создан, идентификатор заказа
    deactivate Dealer

else данные невалидны
    Dealer --> STO : 1.2 ошибка получения токена
    deactivate Dealer

end


@enduml